### ISSUE TITLE
動的ルーティング

### ISSUE THREAD

**Issue by YukiYuigishi** [Growthers/blog#13]

**Comment by kat0h** [comment]
SSGをするのであれば動的レンダリングはできません。
https://github.com/Undecided-Discord/blog/blob/dev/src/pages/authors/%5Bauthor%5D/posts/%5Bslug%5D/index.tsx#L20
参考実装箇所です。

**Comment by Yusuke4869** [comment]
ですね.
いらないので閉じておきます.
