### ISSUE TITLE
Headerの作成

### ISSUE THREAD

**Issue by YukiYuigishi** [Growthers/blog#18]

**Comment by kat0h** [comment]
>「トップ」~~「このサイトについて」~~「カテゴリー」~~「プライバシーポリシー」~~
> これくらいかなー 
> ブログを読みにくる人がいるとして、鯖とか人に興味を持ったならまだしも情報を求めてくる人が記事を書いた人から探すとは考えていないってのが一応の理由です

**Comment by YukiYuigishi** [comment]
「月ごとの記事一覧」なんかがあってもいいかもしれない

**Comment by Yusuke4869** [comment]
#37
