### ISSUE TITLE
1行に2つ以上リンクをいれるとOGPが1つしか取得されない / OGPを非表示にできるようにしたい

### ISSUE THREAD

**Issue by YukiYuigishi** [Growthers/blog#76]
```md
[hoge](http://URL)と[fuga](https://URL)があって...
```
のようにリンクを2つ入れるとOGPが取得されてしまう

**Comment by YukiYuigishi** [comment]
![image](https://user-images.githubusercontent.com/64316110/145229693-37a32bb7-b648-48ac-9ff2-9151bb03a5e3.png)

**Comment by Yusuke4869** [comment]
これは仕様です
ただし, 2つ以上入れたときに1つしかOGPが表示されていないのでそれは修正対象です

**Comment by re-taro** [comment]
OGPが消せると嬉しいかも

**Comment by Yusuke4869** [comment]
これと一緒に対応します
